### ISSUE TITLE
Travis failed with BlockingIOError

### ISSUE THREAD

**Issue by wsdjeg** [Vimjas/covimerage#94]
```
bundle/incsearch.vim/autoload/incsearch/over/modTraceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/covimerage", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/covimerage/cli.py", line 192, in run
    **report_opts)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/covimerage/cli.py", line 278, in report
    skip_covered=skip_covered,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/covimerage/coveragepy.py", line 71, in wrapper
    return f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/covimerage/coveragepy.py", line 129, in report
    omit=omit, skip_covered=skip_covered)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/control.py", line 1041, in report
    return reporter.report(morfs, outfile=file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/summary.py", line 143, in report
    writeout(line[0])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
BlockingIOError: [Errno 11] write could not complete without blocking
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking
make: *** [test_coverage] Error 120
The command ".ci/script.sh" exited with 2.
```

https://travis-ci.org/github/SpaceVim/SpaceVim/jobs/737331417

**Comment by blueyed** [comment]
Is this reproducible, or something flaky?

For reference:
```
/home/travis/virtualenv/python3.6.3/bin/covimerage run nvim -Nu test/vimrc -c 'Vader! test/**'

Running cmd: nvim -Nu test/vimrc -c 'Vader! test/**' --cmd 'profile start /tmp/covimerage.profile.lh0u_yez' --cmd 'profile! file ./*' (in /home/travis/build/SpaceVim/SpaceVim)
```
(https://travis-ci.org/github/SpaceVim/SpaceVim/jobs/737331417#L4722)

**Comment by wsdjeg** [comment]
@blueyed It is reproduceable in neovim, you can checkout the travis-ci status of spacevim master branch, all nvim test is failed.

**Comment by blueyed** [comment]
@wsdjeg did it start to happen only recently?  Do you know what change triggered it then?  Do you have a reference to the last good build?

**Comment by wsdjeg** [comment]
sorry, I do not remember, it has been a long time with failed build.
